import { startsWith } from "zod";
import prisma from "../config/prisma.js";
import { ApiError } from "../utils/ApiError.js";

/**
 * Create a new weighbridge transaction record
 */
export const createTransactionRecord = async ({
  receiptNumber,
  vehicleNumber,
  customerName,
  quantity,
  rateApplied,
  paymentType,
  totalAmount,
  site,
  materialId,
  createdAt,
  clerkId,
}) => {
  const material = await prisma.material.findUnique({
    where: { id: materialId },
  });
  if (!material || !material.isActive) {
    throw new ApiError(404, "Selected material is invalid or no longer active");
  }

  if (!(receiptNumber && vehicleNumber && customerName))
    throw new ApiError(400, "All the filed are required");

  if (paymentType == "CASH" && !(rateApplied || totalAmount))
    throw new ApiError(
      400,
      "Either rate or amount is required for CASH payment",
    );

  if (!rateApplied) rateApplied = totalAmount / quantity;
  if (paymentType && paymentType.toUpperCase() == "CASH" && !totalAmount)
    totalAmount = rateApplied * quantity;

  const newTransaction = await prisma.transaction.create({
    data: {
      vehicleNumber: vehicleNumber.toUpperCase().trim(),
      customerName: customerName.trim(),
      quantity,
      rateApplied,
      totalAmount,
      clerkId,
      materialId,
      site,
      paymentType,
      receiptNumber,
      createdAt,
    },
    include: {
      material: {
        select: { name: true },
      },
      clerk: {
        select: { name: true },
      },
    },
  });

  return newTransaction;
};

/**
 * Fetch transaction by ID for safety verification or manual reprint triggers
 */
export const getTransactionById = async (id) => {
  const transaction = await prisma.transaction.findUnique({
    where: { id },
    include: {
      material: { select: { name: true } },
      clerk: { select: { name: true } },
    },
  });

  if (!transaction) {
    throw new ApiError(404, "Transaction record not found");
  }

  return transaction;
};

/**
 * Fetch all global transactions with advanced administrative filtering
 */
export const getGlobalTransactions = async ({
  page = 1,
  limit = 10,
  search,
  material,
  startDate,
  endDate,
}) => {
  const skip = (page - 1) * limit;

  const whereClause = { isVoided: false };

  if (search) {
    const formattedSearch = search.trim();

    whereClause.OR = [
      { vehicleNumber: { contains: formattedSearch.toUpperCase().trim() } },
      { customerName: { contains: formattedSearch, mode: "insensitive" } },
      { receiptNumber: { startsWith: formattedSearch, mode: "insensitive" } },
    ];
  }

  if (material) {
    // If your schema stores materialId directly on the transaction:
    whereClause.materialId = material;

    // OR if you match by material name string instead, uncomment below:
    // whereClause.material = { name: { contains: material, mode: "insensitive" } };
  }

  if (startDate || endDate) {
    whereClause.createdAt = {};
    if (startDate) whereClause.createdAt.gte = new Date(startDate);
    if (endDate) whereClause.createdAt.lte = new Date(endDate);
  }

  // 🚀 Added raw groupings to aggregate financial metrics in parallel execution
  const [transactions, totalCount, totalsAggregation, cashAggregation] =
    await prisma.$transaction([
      // Paginated Transactions list
      prisma.transaction.findMany({
        where: whereClause,
        skip,
        take: parseInt(limit),
        orderBy: { createdAt: "desc" },
        include: {
          material: { select: { name: true } },
          clerk: { select: { name: true } },
        },
      }),

      // Total Count for Pagination
      prisma.transaction.count({ where: whereClause }),

      // Total Overall Quantity and Cumulative Amount across ALL matching records
      prisma.transaction.aggregate({
        where: whereClause,
        _sum: {
          quantity: true,
          totalAmount: true,
        },
      }),

      // Total Cash Calculation
      prisma.transaction.aggregate({
        where: {
          ...whereClause,
          paymentType: "CASH",
        },
        _sum: {
          totalAmount: true,
        },
      }),
    ]);

  const totalQuantity = totalsAggregation._sum.quantity || 0;
  const overallTotalAmount = totalsAggregation._sum.totalAmount || 0;
  const totalCash = cashAggregation._sum.totalAmount || 0;
  const totalCredit = overallTotalAmount - totalCash;

  return {
    transactions,
    meta: {
      totalCount,
      currentPage: parseInt(page),
      totalPages: Math.ceil(totalCount / limit),
      totalQuantity,
      totalCash,
      totalCredit,
    },
  };
};

/**
 * Fetch only the records generated by a specific clerk during their active shift
 */
export const getClerkShiftTransactions = async (clerkId) => {
  // get the transactions for last 12 hours only
  const twelveHoursAgo = new Date(Date.now() - 12 * 60 * 60 * 1000);

  return await prisma.transaction.findMany({
    where: {
      clerkId,
      createdAt: { gte: twelveHoursAgo },
      isVoided: false,
    },
    orderBy: { createdAt: "desc" },
    include: {
      material: { select: { name: true } },
    },
  });
};

export const getMaxReceiptNumber = async () => {
  const highestTicket = await prisma.transaction.findFirst({
    orderBy: {
      receiptNumber: "desc",
    },
    select: {
      receiptNumber: true,
    },
  });

  return highestTicket ? highestTicket.receiptNumber : 1000;
};
