import prisma from "../config/prisma.js";
import { ApiError } from "../utils/ApiError.js";

/**
 * Create a new weighbridge transaction record
 */
export const createTransactionRecord = async ({
  receiptNumber,
  vehicleNumber,
  customerName,
  netWeight,
  rateApplied,
  paymentType,
  totalAmount,
  site,
  materialId,
  createdAt,
  clerkId,
}) => {
  const material = await prisma.material.findUnique({
    where: { id: materialId },
  });
  if (!material || !material.isActive) {
    throw new ApiError(404, "Selected material is invalid or no longer active");
  }

  if (!(receiptNumber && vehicleNumber && customerName))
    throw new ApiError(400, "All the filed are required");

  if (paymentType == "CASH" && !(rateApplied || totalAmount))
    throw new ApiError(
      400,
      "Either rate or amount is required for CASH payment",
    );

  if (!rateApplied) rateApplied = totalAmount / netWeight;
  if (paymentType && paymentType.toUpperCase() == "CASH" && !totalAmount)
    totalAmount = rateApplied * netWeight;

  const newTransaction = await prisma.transaction.create({
    data: {
      vehicleNumber: vehicleNumber.toUpperCase().trim(),
      customerName: customerName.trim(),
      netWeight,
      rateApplied,
      totalAmount,
      clerkId,
      materialId,
      site,
      paymentType,
      receiptNumber,
      createdAt,
    },
    include: {
      material: {
        select: { name: true },
      },
      clerk: {
        select: { name: true },
      },
    },
  });

  return newTransaction;
};

/**
 * Fetch transaction by ID for safety verification or manual reprint triggers
 */
export const getTransactionById = async (id) => {
  const transaction = await prisma.transaction.findUnique({
    where: { id },
    include: {
      material: { select: { name: true } },
      clerk: { select: { name: true } },
    },
  });

  if (!transaction) {
    throw new ApiError(404, "Transaction record not found");
  }

  return transaction;
};

/**
 * Fetch all global transactions with advanced administrative filtering
 */
export const getGlobalTransactions = async ({
  page = 1,
  limit = 10,
  search,
  startDate,
  endDate,
}) => {
  const skip = (page - 1) * limit;

  // Build dynamic filtering conditions for Prisma
  const whereClause = { isVoided: false };

  // 1. Multi-field text search (Vehicle number or Customer Name)
  if (search) {
    whereClause.OR = [
      { vehicleNumber: { contains: search.toUpperCase().trim() } },
      { customerName: { contains: search, mode: "insensitive" } },
      { receiptNumber: { contains: search, mode: "insensitive" } },
    ];
  }

  // 2. Date Range filters
  if (startDate || endDate) {
    whereClause.createdAt = {};
    if (startDate) whereClause.createdAt.gte = new Date(startDate);
    if (endDate) whereClause.createdAt.lte = new Date(endDate);
  }

  const [transactions, totalCount] = await prisma.$transaction([
    prisma.transaction.findMany({
      where: whereClause,
      skip,
      take: parseInt(limit),
      orderBy: { createdAt: "desc" },
      include: {
        material: { select: { name: true } },
        clerk: { select: { name: true } },
      },
    }),
    prisma.transaction.count({ where: whereClause }),
  ]);

  return {
    transactions,
    meta: {
      totalCount,
      currentPage: parseInt(page),
      totalPages: Math.ceil(totalCount / limit),
    },
  };
};

/**
 * Fetch only the records generated by a specific clerk during their active shift
 */
export const getClerkShiftTransactions = async (clerkId) => {
  // get the transactions for last 12 hours only
  const twelveHoursAgo = new Date(Date.now() - 12 * 60 * 60 * 1000);

  return await prisma.transaction.findMany({
    where: {
      clerkId,
      createdAt: { gte: twelveHoursAgo },
      isVoided: false,
    },
    orderBy: { createdAt: "desc" },
    include: {
      material: { select: { name: true } },
    },
  });
};

export const getMaxReceiptNumber = async () => {
  const highestTicket = await prisma.transaction.findFirst({
    orderBy: {
      receiptNumber: "desc",
    },
    select: {
      receiptNumber: true,
    },
  });

  return highestTicket ? highestTicket.receiptNumber : 1000;
};
